import "./globals.css";
import Provider from "./Provider";
import { CartProvider } from "@/context/CartContext";
import * as Sentry from "@sentry/nextjs";

export const metadata = {
  title: "CountryCraft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Sentry.ErrorBoundary fallback={"An error has occurred. Please reload or try again later."}>
          <Provider>
            <CartProvider>
              <div className="h-dvh">

                {children}
              </div>
            </CartProvider>
          </Provider>
        </Sentry.ErrorBoundary>
      </body>
    </html>
  );
}
