import "./globals.css";
import Provider from "./Provider";
import { CartProvider } from "@/context/CartContext";

export const metadata = {
  title: "CountryCraft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <CartProvider>
            {children}
          </CartProvider>
        </Provider>
      </body>
    </html>
  );
}
