import "./globals.css";
import Provider from "./Provider";

export const metadata = {
  title: "CountryCraft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
